INSERT INTO r022doc (tipdoc, destip) VALUES(800, 'Signaturo - Admissão');
INSERT INTO r022doc (tipdoc, destip) VALUES(801, 'Signaturo - Férias');
INSERT INTO r022doc (tipdoc, destip) VALUES(802, 'Signaturo - Cartão Ponto');
INSERT INTO r022doc (tipdoc, destip) VALUES(803, 'Signaturo - Rescisão');
INSERT INTO r022doc (tipdoc, destip) VALUES(804, 'Signaturo - Advertência');
INSERT INTO r022doc (tipdoc, destip) VALUES(805, 'Signaturo - Suspensão');
INSERT INTO r022doc (tipdoc, destip) VALUES(806, 'Signaturo - Acordo de Compensação');
INSERT INTO r022doc (tipdoc, destip) VALUES(807, 'Signaturo - Acordo de BH');
INSERT INTO r022doc (tipdoc, destip) VALUES(808, 'Signaturo - Holerite');
INSERT INTO r022doc (tipdoc, destip) VALUES(809, 'Signaturo - Afastamento INSS');
INSERT INTO r022doc (tipdoc, destip) VALUES(898, 'Signaturo - Download');
INSERT INTO r022doc (tipdoc, destip) VALUES(899, 'Signaturo - Outros');